## Mathematics for Data Science

Resources used for this notebook:
- https://towardsdatascience.com/introduction-to-vectors-and-matrices-using-python-for-data-science-e836e014eb12


### Content
- [Linear Algebra](#1)


minimum Math skills: Linear Algebra, vector calculus and probability theory

<a id='1'></a>
### Linear Algebra

Basic Algebra definitions:
- Scalar: is a single numerical value
- Vector: is an array of numerical values, e.g. a numericla column in a DataFrame
- Matrix: is a 2D aray with in the shape of m rows * n columns, e.g. the entire DataFrame 
- Tensor: is a n-dimensional array where n>2

In [1]:
#imports
import numpy as np

#### Create an array

In [5]:
# create an array x
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [7]:
# check the shape
x.shape

(5,)

#### Create a matrix

In [10]:
# create a matrix (2d array))
x1 = np.array([[1,2], [3,4], [5,6]])
x1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
x1.shape
# 3 rows / 2 columns

(3, 2)

#### Transpose a matrix 

In [13]:
# with the T attribute
x1_t = x1.T
x1_t

array([[1, 3, 5],
       [2, 4, 6]])

In [18]:
# shape after transpose
x1_t.shape
# 2 rows / 3 columns

(2, 3)

In [14]:
# with numpy function transpose()
np.transpose(x1)

array([[1, 3, 5],
       [2, 4, 6]])

#### Mathematical operations and Broadcasting in Matrices

you can performe mathimatical operations on matrices like addition, substraction, multiplication, division etc.

In [27]:
m1 = np.array([[1, 2], [3, 4], [5, 6]])
# create an matrix with ones in the corresponding shape
m2 = np.ones(shape=(3,2))

In [32]:
m1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
m2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
# addition
m1 + m2

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [33]:
# substraction
m1 - m2

array([[0., 1.],
       [2., 3.],
       [4., 5.]])

In [34]:
# multiplication
m1 * m2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [35]:
# division
m1 / m2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [37]:
# squared
m1 ** m2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### Broadcasting 
- Broadcasting is the process by which different types of arrays, i.e. arrays in different forms, are converted into a mutually compatible form using arithmetic operations.

In [41]:
# add a scalar
a = 2

In [39]:
m1 + a

array([[3, 4],
       [5, 6],
       [7, 8]])

In [40]:
m1 ** a

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

##### Adding a matrix with a different shape
When adding a matrix with a different shape the 'smaller' matrix gets extended to match the 'bigger' one.

In [45]:
# add a matrix with a different shape
arr = np.array([[1], [2], [3]])
arr

array([[1],
       [2],
       [3]])

In [50]:
arr1 = np.array([[1, 2]])
arr1

array([[1, 2]])

In [46]:
m1 + arr

array([[2, 3],
       [5, 6],
       [8, 9]])

In [51]:
m1 + arr1

array([[2, 4],
       [4, 6],
       [6, 8]])

You only can add matrices with different shaped when either the column or the row shape is the same

In [58]:
# lets create matrices that has a diffent shape
arr2 = np.array([[1, 2, 3]])
arr3 = np.array([[1], [2], [3], [4]])

In [53]:
m1 + arr2
# should return an Error

ValueError: operands could not be broadcast together with shapes (3,2) (1,3) 

In [54]:
m1 + arr3
# should return an Error

ValueError: operands could not be broadcast together with shapes (3,2) (4,1) 